services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "14268"
    networks:
      - network-gin-tracing
  go-tracing-service:
    build:
      dockerfile: $PWD/Dockerfile
      context: ./
    ports:
      - "8080:8080"
    command:
      - "/bin/sh"
      - "-c"
      - "/go/bin/go-tracing"
    networks:
      - network-gin-tracing
networks:
  network-gin-tracing:
